### ISSUE TITLE
VET crashing with "ImportError: cannot import name data_table"

### ISSUE THREAD

**Issue by brennanhughey** [gwpy/gwsumm#135]
VET is now crashing at CIT, LHO and LLO with "ImportError: cannot import name data_table"

I was able to successfully run at LHO on November 8th, and an identical run now fails.

```
/home/bhughey/public_html/VET/SN/dec23test/vetcommandline.sh
```

produces the error below:

```
------------------------------------------------------------------------------
Welcome to the GW summary information system command-line interface
------------------------------------------------------------------------------

This is process 511252
You have selected gps mode.
Start time 2015-12-23 09:59:43.000 (1134900000.0)
End time: 2015-12-28 01:06:23.000 (1135300000.0)
Output directory: /home/bhughey/public_html/VET/SN/dec23test/1134900000-1135300000

Loading configuration...
Traceback (most recent call last):
  File "/home/detchar/opt/gwpysoft-2.7/bin/gw_summary", line 473, in <module>
    plugins = config.load_plugins()
  File "/home/detchar/opt/gwpysoft-2.7/lib/python2.7/site-packages/gwsumm/config.py", line 241, in load_plugins
    mods.append(import_module(plugin))
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/lib64/python2.7/site-packages/ROOT.py", line 352, in _importhook
    return _orig_ihook( name, *args, **kwds )
  File "/home/detchar/opt/gwpysoft-2.7/lib/python2.7/site-packages/gwvet/tabs.py", line 34, in <module>
    from gwsumm.html import (data_table, markup)
ImportError: cannot import name data_table
```

**Comment by duncanmmacleod** [comment]
This was resolved by gwpy/vet@994df0a, and has been installed across the LDG.
